import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import LoginButton from "./components/LoginButton";
import Logo from "./components/Logo"; 



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen">
        {/* Navbar */}
        <header className="bg-white shadow-md p-4 flex justify-between items-center">
          <div className="flex items-center">
            <Logo />
          </div>
          <div>
            <LoginButton />
            <button className="bg-blue-500 text-white px-4 py-2 rounded-md">
              Create Store
            </button>
          </div>
        </header>

        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}